/**
 * The demo clip's amplitude envelope, as bar heights in percent.
 *
 * Generated by `scripts/build-demo-waveform.py` from `public/demo/sample.mp3` — these
 * are real measured peaks, not decoration. Re-run that script if the clip changes.
 *
 * Baked rather than computed at runtime so the true shape is on screen before the
 * visitor presses play, and so it survives into the static HTML export.
 */
export const DEMO_WAVEFORM: readonly number[] = [
   10.8,  11.2,  62.3,  64.1,  57.1,  51.7,  40.1,  40.3,
   41.1,  39.0,  38.0,  32.6,  15.2,  11.6,  10.1,  53.4,
   59.0,  57.0,  54.5,  52.5,  42.1,  27.4,  93.0, 100.0,
   96.3,  82.1,  71.3,  29.9,  58.9,  73.2,  67.1,  58.6,
   57.1,  49.9,  35.1,  41.5,  63.7,  66.6,  62.2,  62.1,
   33.4,  11.9,  89.8,  90.3,  79.9,  66.6,  61.3,  41.1,
   35.2,  55.9,  56.0,  51.6,  44.7,  41.0,  15.0,  57.9,
   65.6,  64.3,  63.8,  57.1,  41.3,  21.9,  47.7,  55.8,
   53.7,  51.1,  46.8,  37.2,  15.2,  39.2,  52.7,  52.4,
   51.0,  47.6,  45.8,  38.1,  58.3,  58.2,  58.7,  59.3,
   28.2,  16.0,  71.3,  70.9,  64.3,  58.0,  37.7,  14.9,
   86.2,  86.9,  79.6,  74.6,  68.0,  66.4,  59.4,  52.0,
   39.4,  32.7,  27.3,  71.4,  75.8,  59.4,  35.8,  73.5,
   73.3,  60.3,  50.0,  46.7,  42.6,  23.7,  21.5,  12.9,
];
