/**
 * The demo clip's amplitude envelope, as bar heights in percent.
 *
 * Generated by `scripts/build-demo-waveform.py` from `public/demo/sample.mp3` — these
 * are real measured peaks, not decoration. Re-run that script if the clip changes.
 *
 * Baked rather than computed at runtime so the true shape is on screen before the
 * visitor presses play, and so it survives into the static HTML export.
 */
export const DEMO_WAVEFORM: readonly number[] = [
   11.2,  64.1,  57.1,  40.3,  41.1,  38.0,  15.2,  53.4,
   59.0,  54.5,  42.1, 100.0,  96.3,  71.3,  73.2,  67.1,
   57.1,  41.5,  66.6,  62.2,  33.4,  90.3,  79.9,  61.3,
   55.9,  56.0,  44.7,  57.9,  65.6,  63.8,  41.3,  55.8,
   53.7,  46.8,  39.2,  52.7,  51.0,  45.8,  58.3,  59.3,
   28.4,  71.3,  64.3,  37.7,  86.9,  79.6,  68.0,  59.4,
   39.4,  71.4,  75.8,  73.5,  73.3,  50.0,  42.6,  21.5,
];
