#!/usr/bin/env python3
"""Generate the landing demo's waveform from the actual clip (12-3).

    python3 scripts/build-demo-waveform.py

Reads `public/demo/sample.mp3`, measures its amplitude envelope, and writes
`src/components/landing/demoWaveform.ts`.

**Why precompute rather than draw it live.** The demo only decodes the clip when the visitor
presses play, so a waveform derived at runtime would appear *after* the click — exactly when
it stops being an invitation and becomes a progress bar. Baking it means the real shape is on
screen the moment the page loads, it renders into the static HTML export, and it costs a few
hundred bytes instead of decoding 168 KB of audio nobody asked for yet.

It is still the real waveform: these are peaks measured from the same file the demo plays.
Re-run this whenever `public/demo/sample.mp3` changes.
"""

import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
CLIP = ROOT / "public" / "demo" / "sample.mp3"
OUT = ROOT / "src" / "components" / "landing" / "demoWaveform.ts"

# Enough bars to read as a waveform, few enough that each stays a comfortable click target
# and the array stays small in the bundle.
BARS = 56

# Peaks, not RMS: RMS of a harmonica line is fairly flat and draws a brick. The peak envelope
# keeps the phrasing visible — you can see where the notes are.
#
# Then a gamma lift, because raw peaks on a quiet recording leave most bars near the floor and
# the shape disappears. 0.65 opens up the quiet half without flattening the loud one.
GAMMA = 0.65
FLOOR = 6.0  # percent — so silence is still a visible tick rather than a gap


def main() -> None:
    if not CLIP.exists():
        raise SystemExit(f"missing clip: {CLIP}")

    # ffmpeg decodes the MP3 to raw mono float32; numpy does the rest.
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(CLIP), "-ac", "1", "-f", "f32le", "-"],
        check=True, stdout=subprocess.PIPE,
    ).stdout
    samples = np.frombuffer(raw, dtype=np.float32)
    if samples.size == 0:
        raise SystemExit("decoded no audio")

    buckets = np.array_split(samples, BARS)
    peaks = np.array([float(np.abs(b).max()) for b in buckets])
    peaks /= peaks.max() or 1.0

    heights = FLOOR + (100.0 - FLOOR) * (peaks ** GAMMA)
    values = [round(float(h), 1) for h in heights]

    rows = "\n".join(
        "  " + ", ".join(f"{v:5.1f}" for v in values[i:i + 8]) + ","
        for i in range(0, len(values), 8)
    )

    OUT.write_text(
        "/**\n"
        " * The demo clip's amplitude envelope, as bar heights in percent.\n"
        " *\n"
        " * Generated by `scripts/build-demo-waveform.py` from `public/demo/sample.mp3` — these\n"
        " * are real measured peaks, not decoration. Re-run that script if the clip changes.\n"
        " *\n"
        " * Baked rather than computed at runtime so the true shape is on screen before the\n"
        " * visitor presses play, and so it survives into the static HTML export.\n"
        " */\n"
        f"export const DEMO_WAVEFORM: readonly number[] = [\n{rows}\n];\n"
    )

    print(f"{CLIP.relative_to(ROOT)} → {OUT.relative_to(ROOT)}")
    print(f"  {samples.size} samples → {BARS} bars, {OUT.stat().st_size} bytes")
    spark = "".join(" ▁▂▃▄▅▆▇█"[min(8, int(v / 12.5))] for v in values)
    print(f"  {spark}")


if __name__ == "__main__":
    main()
