/**
 * Verification harness for the HSA v2 engine. Replaces `verify-spectral-pitch.ts`.
 *
 * Unlike its predecessor this is a **regression gate, not a measurement tool**: assertions 1
 * and 2 are equality claims. The engine is a port of `HSA_v2_polyphonic.ipynb`, so "it
 * computes what the notebook computes" is the correctness claim, and only a frame-for-frame
 * comparison against the notebook's own output can substantiate it.
 *
 * Assertion 1 earns its place separately. `CqtAnalyzer` slices the audio so the UI can paint
 * between chunks, and a wrong slice produces plausible-looking numbers rather than an error —
 * which assertion 2 would then attribute to the port.
 *
 * Fixtures in `scripts/fixtures/hsa/`, regenerated by
 * `/Users/theo/audio_analysis/dump_hsa_fixture.py`. They are PCM at 44.1kHz so nothing here
 * has to decode or resample — `OfflineAudioContext` does not exist under `tsx`.
 *
 * Run: npx tsx scripts/verify-hsa.ts
 */

import { readFileSync } from 'node:fs';
import { CqtAnalyzer, HSA_CQT_CONFIG } from '../src/audio/dsp/cqt';
import { analyzePoly, MAX_VOICES } from '../src/audio/dsp/hsaPoly';
import { detectReattacks, DEFAULT_REATTACK_CONFIG } from '../src/audio/segmenters/reattack';

const FIXTURES = `${__dirname}/fixtures/hsa`;
const SAMPLE_RATE = 44100;

let failures = 0;

function check(label: string, passed: boolean, detail: string): void {
  if (!passed) failures++;
  console.log(`${passed ? '  ok  ' : ' FAIL '} ${label} — ${detail}`);
}

/** Harmonic-rich material: a pure sine gives a four-harmonic sum nothing to sum. */
function synth(seconds: number, pitches: { hz: number; from: number; to: number }[]): Float32Array {
  const n = Math.floor(seconds * SAMPLE_RATE);
  const y = new Float32Array(n);
  for (const { hz, from, to } of pitches) {
    const i0 = Math.floor(from * SAMPLE_RATE);
    const i1 = Math.min(n, Math.floor(to * SAMPLE_RATE));
    for (let i = i0; i < i1; i++) {
      const t = i / SAMPLE_RATE;
      for (let h = 1; h <= 8; h++) {
        if (hz * h >= 0.45 * SAMPLE_RATE) break;
        y[i] += Math.pow(h, -0.6) * Math.sin(2 * Math.PI * hz * h * t);
      }
    }
  }
  let peak = 0;
  for (const v of y) peak = Math.max(peak, Math.abs(v));
  if (peak > 0) for (let i = 0; i < n; i++) y[i] = (0.9 * y[i]) / peak;
  return y;
}

async function main(): Promise<void> {
  console.log('\n=== 1. Chunked CQT equals whole-file CQT ===\n');
  {
    const audio = synth(25, [
      { hz: 392.0,  from: 0.3,  to: 6.0 },
      { hz: 523.25, from: 0.3,  to: 6.0 },
      { hz: 880.0,  from: 8.0,  to: 14.0 },
      { hz: 293.66, from: 16.0, to: 24.0 },
    ]);
    const cqt     = await CqtAnalyzer.create(HSA_CQT_CONFIG);
    const whole   = cqt.analyzeWhole(audio);
    const chunked = await cqt.analyze(audio);
    cqt.dispose();

    check('frame counts match', whole.frameCount === chunked.frameCount,
          `whole ${whole.frameCount}, chunked ${chunked.frameCount}`);

    let worst = 0;
    let worstFrame = -1;
    const n = Math.min(whole.data.length, chunked.data.length);
    for (let i = 0; i < n; i++) {
      const d = Math.abs(whole.data[i] - chunked.data[i]);
      if (d > worst) { worst = d; worstFrame = Math.floor(i / whole.nBins); }
    }
    let peak = 0;
    for (const v of whole.data) peak = Math.max(peak, v);
    check('chunked CQT is bit-comparable to whole-file',
          worst < 1e-5 * peak,
          `worst abs diff ${worst.toExponential(2)} at frame ${worstFrame} (peak ${peak.toFixed(3)})`);
  }

  console.log('\n=== 2. Poly pass matches the Python reference ===\n');
  {
    for (const name of ['synth_g4c5', '34blow']) {
      const raw = readFileSync(`${FIXTURES}/${name}.f32`);
      const pcm = new Float32Array(raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength));
      const expected = JSON.parse(readFileSync(`${FIXTURES}/${name}.json`, 'utf8')) as {
        frameCount: number; voiced: boolean[]; pitches: number[][];
      };

      const analyzer = await CqtAnalyzer.create(HSA_CQT_CONFIG);
      const cqt = await analyzer.analyze(pcm);
      analyzer.dispose();

      const voiced = Uint8Array.from(expected.voiced, (v) => (v ? 1 : 0));
      const poly   = analyzePoly(cqt, HSA_CQT_CONFIG, voiced);

      let same = 0;
      let firstBad = -1;
      const total = Math.min(poly.frameCount, expected.frameCount);
      for (let f = 0; f < total; f++) {
        const got: number[] = [];
        for (let s = 0; s < MAX_VOICES; s++) {
          const p = poly.pitch[f * MAX_VOICES + s];
          if (!Number.isFinite(p)) continue;
          // The notebook's rel_threshold, applied here rather than during analysis — see
          // the divergence note in hsaPoly.ts.
          if (s > 0 && poly.salience[f * MAX_VOICES + s] < 0.60 * poly.sFirst[f]) continue;
          got.push(Math.round(p));
        }
        got.sort((a, b) => a - b);
        const want = expected.pitches[f];
        if (got.length === want.length && got.every((v, i) => v === want[i])) same++;
        else if (firstBad < 0) firstBad = f;
      }
      check(`${name}: pitch sets match Python`, same === total,
            `${same}/${total} frames identical` +
            (firstBad >= 0 ? `, first mismatch at frame ${firstBad}` : ''));
    }
  }

  console.log('\n=== 3. Re-attack detection ===\n');
  {
    const HOP_MS = (1000 * HSA_CQT_CONFIG.hop) / HSA_CQT_CONFIG.sampleRate;
    const frames = (ms: number) => Math.round(ms / HOP_MS);

    /** Envelopes built directly — this tests the state machine, not the DSP. */
    const envelope = (spec: { level: number; ms: number }[]): Float32Array => {
      const out: number[] = [];
      for (const { level, ms } of spec) for (let i = 0; i < frames(ms); i++) out.push(level);
      return Float32Array.from(out);
    };
    const allVoiced = (n: number) => Uint8Array.from({ length: n }, () => 1);
    const hits = (e: Float32Array, v = allVoiced(e.length)) =>
      detectReattacks(e, v, HOP_MS, DEFAULT_REATTACK_CONFIG);

    const clean = envelope([
      { level: 0.5, ms: 300 }, { level: 0.02, ms: 120 }, { level: 0.5, ms: 300 },
    ]);
    check('a clean repeat splits exactly once', hits(clean).length === 1,
          `${hits(clean).length} split(s) at frame(s) [${hits(clean)}]`);

    const shallow = envelope([
      { level: 0.5, ms: 300 }, { level: 0.45, ms: 120 }, { level: 0.5, ms: 300 },
    ]);
    check('a shallow dip does not split', hits(shallow).length === 0,
          'dip never reaches dipRatio 0.35');

    const brief = envelope([
      { level: 0.5, ms: 300 }, { level: 0.02, ms: 8 }, { level: 0.5, ms: 300 },
    ]);
    check('a dip shorter than minDipMs does not split', hits(brief).length === 0,
          '8ms dip, under one frame');

    // The case that moved the constants: 5Hz at 50% depth has a 100ms half-period, well past
    // minDipMs, and a depth well past pMPM's old dipRatio of 0.5.
    const n = frames(3000);
    const vibrato = new Float32Array(n);
    for (let i = 0; i < n; i++) {
      const phase = 2 * Math.PI * 5 * ((i * HOP_MS) / 1000);
      vibrato[i] = 0.5 * (1 - 0.5 * 0.5 * (1 - Math.cos(phase)));
    }
    check('5Hz vibrato at 50% depth produces no splits', hits(vibrato).length === 0,
          `${hits(vibrato).length} split(s)`);

    const quiet = envelope([
      { level: 0.0005, ms: 300 }, { level: 0.00002, ms: 120 }, { level: 0.0005, ms: 300 },
    ]);
    check('below the noise floor, nothing splits',
          detectReattacks(quiet, new Uint8Array(quiet.length), HOP_MS, DEFAULT_REATTACK_CONFIG).length === 0,
          'peak never clears minPeakRmsFloor');

    const four = envelope([
      { level: 0.5, ms: 250 }, { level: 0.02, ms: 120 },
      { level: 0.5, ms: 250 }, { level: 0.02, ms: 120 },
      { level: 0.5, ms: 250 }, { level: 0.02, ms: 120 },
      { level: 0.5, ms: 250 },
    ]);
    check('four articulations give three splits', hits(four).length === 3,
          `${hits(four).length} split(s) at [${hits(four)}]`);
  }

  console.log('');
  if (failures > 0) {
    console.log(`${failures} failure(s)\n`);
    process.exit(1);
  }
  console.log('All checks passed\n');
}

main().catch((err) => { console.error(err); process.exit(1); });
